import { useMemo, useState, useEffect } from 'react';
import { ChevronDown, ChevronUp, Plus, Trash2, Building2 } from 'lucide-react';
import { supabase } from '../../../lib/supabase';
import { useAuth } from '../../../contexts/AuthContext';
import SectionGrade from '../../SectionGrade';
import OutcomePanel from '../OutcomePanel';
import ModuleActions from '../ModuleActions';
import RatingRadio from '../../RatingRadio';
import { sanitizeModuleInstancePayload } from '../../../utils/modulePayloadSanitizer';

interface Document {
  id: string;
  document_type: string;
  title: string;
  assessment_date: string;
  assessor_name: string | null;
  assessor_role: string | null;
}

interface ModuleInstance {
  id: string;
  module_key: string;
  outcome: string | null;
  completed_at: string | null;
  assessor_notes: string;
  data: Record<string, any>;
  updated_at: string;
}

interface RiskEngineeringFormProps {
  moduleInstance: ModuleInstance;
  document: Document;
  onSaved: () => void;
}

interface ConstructionElement {
  element: string;
  type_material: string;
  fire_resistance: string;
  comments: string;
}

interface FireProtectionItem {
  system: string;
  provided: string;
  coverage_extent: string;
  standard: string;
  comments: string;
}

interface NaturalHazard {
  id: string;
  type: string;
  description: string;
  mitigationMeasures: string;
}

interface SectionGrades {
  construction: number;
  fire_protection: number;
  management_systems: number;
  natural_hazards: number;
  business_continuity: number;
  loss_expectancy: number;
}

interface Recommendation {
  id: string;
  hazard: string;
  description: string;
  client_response: string;
  status: string;
  isAutoGenerated?: boolean;
  sourceRatingField?: string;
  priority?: 'Critical' | 'High' | 'Medium' | 'Low';
  driver_dimension?: 'construction' | 'fire_protection' | 'management_systems' | 'natural_hazards' | 'business_continuity' | 'loss_expectancy';
}

export default function RiskEngineeringForm({ moduleInstance, document, onSaved }: RiskEngineeringFormProps) {
  const { profile } = useAuth();
  const d = moduleInstance.data || {};

  const getTodayDate = () => {
    const today = new Date();
    return today.toISOString().split('T')[0];
  };

  const initial = {
    // Document Control
    docControl: d.docControl ?? {
      assessorName: profile?.name || '',
      assessorRole: '',
      assessmentDate: getTodayDate(),
      reviewDate: '',
      siteName: document.title || '',
      scopeLimitations: '',
      standardsFrameworks: '',
    },

    // Construction Table
    constructionElements: d.constructionElements ?? [
      { element: 'Frame', type_material: '', fire_resistance: '', comments: '' },
      { element: 'External Walls', type_material: '', fire_resistance: '', comments: '' },
      { element: 'Roof', type_material: '', fire_resistance: '', comments: '' },
      { element: 'Floors', type_material: '', fire_resistance: '', comments: '' },
      { element: 'Compartments/Fire Stopping', type_material: '', fire_resistance: '', comments: '' }
    ],

    // Fire Protection Table
    fireProtectionItems: d.fireProtectionItems ?? [
      { system: 'Sprinklers', provided: 'No', coverage_extent: '', standard: '', comments: '' },
      { system: 'Detection & Alarm', provided: 'No', coverage_extent: '', standard: '', comments: '' },
      { system: 'Fire Water Supply', provided: 'No', coverage_extent: '', standard: '', comments: '' },
      { system: 'Hydrants/Hose Reels', provided: 'No', coverage_extent: '', standard: '', comments: '' },
      { system: 'Portable Extinguishers', provided: 'No', coverage_extent: '', standard: '', comments: '' },
      { system: 'Gas Suppression', provided: 'No', coverage_extent: '', standard: '', comments: '' }
    ],

    // Management Systems
    commitmentLossPrevention: d.commitmentLossPrevention ?? '',
    commitmentLossPrevention_rating: d.commitmentLossPrevention_rating ?? 3,
    fireEquipmentTesting: d.fireEquipmentTesting ?? '',
    fireEquipmentTesting_rating: d.fireEquipmentTesting_rating ?? 3,
    controlHotWork: d.controlHotWork ?? '',
    controlHotWork_rating: d.controlHotWork_rating ?? 3,
    smoking: d.smoking ?? '',
    smoking_rating: d.smoking_rating ?? 3,
    housekeeping: d.housekeeping ?? '',
    housekeeping_rating: d.housekeeping_rating ?? 3,
    impairmentProcedures: d.impairmentProcedures ?? '',
    impairmentProcedures_rating: d.impairmentProcedures_rating ?? 3,
    electricalSafety: d.electricalSafety ?? '',
    electricalSafety_rating: d.electricalSafety_rating ?? 3,
    trainingEmergencyResponse: d.trainingEmergencyResponse ?? '',
    trainingEmergencyResponse_rating: d.trainingEmergencyResponse_rating ?? 3,
    securityArson: d.securityArson ?? '',
    securityArson_rating: d.securityArson_rating ?? 3,
    lossHistory: d.lossHistory ?? '',
    lossHistory_rating: d.lossHistory_rating ?? 3,
    contractorManagement: d.contractorManagement ?? '',
    contractorManagement_rating: d.contractorManagement_rating ?? 3,
    emergencyPlanning: d.emergencyPlanning ?? '',
    emergencyPlanning_rating: d.emergencyPlanning_rating ?? 3,

    // Loss Expectancy
    selectedCurrency: d.selectedCurrency ?? 'GBP',
    pdSumInsured: d.pdSumInsured ?? '0',
    biSumInsured: d.biSumInsured ?? '0',
    indemnityPeriod: d.indemnityPeriod ?? '12',
    emlPdPercent: d.emlPdPercent ?? 25,
    emlBiPercent: d.emlBiPercent ?? 25,
    mflPdPercent: d.mflPdPercent ?? 100,
    mflBiPercent: d.mflBiPercent ?? 100,
    lossExpectancyComments: d.lossExpectancyComments ?? '',

    // Natural Hazards
    naturalHazards: d.naturalHazards ?? [],

    // Business Continuity
    businessInterruption: d.businessInterruption ?? '',
    contingencyPlanning: d.contingencyPlanning ?? '',
    supplyChain: d.supplyChain ?? '',

    // Section Grades
    sectionGrades: (d.sectionGrades ?? {
      construction: 3,
      fire_protection: 3,
      management_systems: 3,
      natural_hazards: 3,
      business_continuity: 3,
      loss_expectancy: 3
    }) as SectionGrades,

    // Recommendations
    recommendations: d.recommendations ?? [],
  };

  // State
  const [docControl, setDocControl] = useState(initial.docControl);
  const [constructionElements, setConstructionElements] = useState<ConstructionElement[]>(initial.constructionElements);
  const [fireProtectionItems, setFireProtectionItems] = useState<FireProtectionItem[]>(initial.fireProtectionItems);

  const [commitmentLossPrevention, setCommitmentLossPrevention] = useState(initial.commitmentLossPrevention);
  const [commitmentLossPrevention_rating, setCommitmentLossPreventionRating] = useState(initial.commitmentLossPrevention_rating);
  const [fireEquipmentTesting, setFireEquipmentTesting] = useState(initial.fireEquipmentTesting);
  const [fireEquipmentTesting_rating, setFireEquipmentTestingRating] = useState(initial.fireEquipmentTesting_rating);
  const [controlHotWork, setControlHotWork] = useState(initial.controlHotWork);
  const [controlHotWork_rating, setControlHotWorkRating] = useState(initial.controlHotWork_rating);
  const [smoking, setSmoking] = useState(initial.smoking);
  const [smoking_rating, setSmokingRating] = useState(initial.smoking_rating);
  const [housekeeping, setHousekeeping] = useState(initial.housekeeping);
  const [housekeeping_rating, setHousekeepingRating] = useState(initial.housekeeping_rating);
  const [impairmentProcedures, setImpairmentProcedures] = useState(initial.impairmentProcedures);
  const [impairmentProcedures_rating, setImpairmentProceduresRating] = useState(initial.impairmentProcedures_rating);
  const [electricalSafety, setElectricalSafety] = useState(initial.electricalSafety);
  const [electricalSafety_rating, setElectricalSafetyRating] = useState(initial.electricalSafety_rating);
  const [trainingEmergencyResponse, setTrainingEmergencyResponse] = useState(initial.trainingEmergencyResponse);
  const [trainingEmergencyResponse_rating, setTrainingEmergencyResponseRating] = useState(initial.trainingEmergencyResponse_rating);
  const [securityArson, setSecurityArson] = useState(initial.securityArson);
  const [securityArson_rating, setSecurityArsonRating] = useState(initial.securityArson_rating);
  const [lossHistory, setLossHistory] = useState(initial.lossHistory);
  const [lossHistory_rating, setLossHistoryRating] = useState(initial.lossHistory_rating);
  const [contractorManagement, setContractorManagement] = useState(initial.contractorManagement);
  const [contractorManagement_rating, setContractorManagementRating] = useState(initial.contractorManagement_rating);
  const [emergencyPlanning, setEmergencyPlanning] = useState(initial.emergencyPlanning);
  const [emergencyPlanning_rating, setEmergencyPlanningRating] = useState(initial.emergencyPlanning_rating);

  const [selectedCurrency, setSelectedCurrency] = useState(initial.selectedCurrency);
  const [pdSumInsured, setPdSumInsured] = useState(initial.pdSumInsured);
  const [biSumInsured, setBiSumInsured] = useState(initial.biSumInsured);
  const [indemnityPeriod, setIndemnityPeriod] = useState(initial.indemnityPeriod);
  const [emlPdPercent, setEmlPdPercent] = useState(initial.emlPdPercent);
  const [emlBiPercent, setEmlBiPercent] = useState(initial.emlBiPercent);
  const [mflPdPercent, setMflPdPercent] = useState(initial.mflPdPercent);
  const [mflBiPercent, setMflBiPercent] = useState(initial.mflBiPercent);
  const [lossExpectancyComments, setLossExpectancyComments] = useState(initial.lossExpectancyComments);

  const [naturalHazards, setNaturalHazards] = useState<NaturalHazard[]>(initial.naturalHazards);
  const [businessInterruption, setBusinessInterruption] = useState(initial.businessInterruption);
  const [contingencyPlanning, setContingencyPlanning] = useState(initial.contingencyPlanning);
  const [supplyChain, setSupplyChain] = useState(initial.supplyChain);

  const [sectionGrades, setSectionGrades] = useState<SectionGrades>(initial.sectionGrades);
  const [recommendations, setRecommendations] = useState<Recommendation[]>(initial.recommendations);

  const [isSaving, setIsSaving] = useState(false);
  const [lastSaved, setLastSaved] = useState<string | null>(null);
  const [expandedSections, setExpandedSections] = useState<Record<string, boolean>>({});

  const handleSectionGradeChange = (section: keyof SectionGrades, value: number) => {
    setSectionGrades(prev => ({ ...prev, [section]: value }));
  };

  // Helper to parse string numbers with commas
  const toNum = (s: string | number) => {
    return Number(String(s).replace(/,/g, '').trim() || 0);
  };

  // Currency formatting
  const formatCurrency = (value: number) => {
    const symbols: Record<string, string> = { GBP: '£', USD: '$', EUR: '€' };
    const symbol = symbols[selectedCurrency] || selectedCurrency;
    return `${symbol}${value.toLocaleString('en-GB', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
  };

  // Calculate loss metrics
  const lossMetrics = useMemo(() => {
    const pd = toNum(pdSumInsured);
    const bi = toNum(biSumInsured);

    const emlPd = pd * emlPdPercent / 100;
    const emlBi = bi * emlBiPercent / 100;
    const emlTotal = emlPd + emlBi;

    const mflPd = pd * mflPdPercent / 100;
    const mflBi = bi * mflBiPercent / 100;
    const mflTotal = mflPd + mflBi;

    return { pd, bi, emlPd, emlBi, emlTotal, mflPd, mflBi, mflTotal };
  }, [pdSumInsured, biSumInsured, emlPdPercent, emlBiPercent, mflPdPercent, mflBiPercent]);

  const { pd, bi, emlPd, emlBi, emlTotal, mflPd, mflBi, mflTotal } = lossMetrics;

  // Auto-generate recommendations based on poor ratings
  useEffect(() => {
    const sections: Array<{ key: keyof SectionGrades; name: string }> = [
      { key: 'construction', name: 'Construction' },
      { key: 'fire_protection', name: 'Fire Protection' },
      { key: 'management_systems', name: 'Management Systems' },
      { key: 'natural_hazards', name: 'Natural Hazards' },
      { key: 'business_continuity', name: 'Business Continuity' },
      { key: 'loss_expectancy', name: 'Loss Expectancy' }
    ];

    sections.forEach(section => {
      const rating = sectionGrades[section.key];
      const sourceField = `section_grade_${section.key}`;

      const existingRecommendation = recommendations.find(
        (rec) => rec.sourceRatingField === sourceField && rec.isAutoGenerated
      );

      if (rating <= 2) {
        if (!existingRecommendation) {
          const severity = rating === 1 ? 'Critical' : 'High';
          const newRec: Recommendation = {
            id: crypto.randomUUID(),
            hazard: `${section.name} - ${rating === 1 ? 'Poor' : 'Tolerable'} Rating`,
            description: `The ${section.name.toLowerCase()} section has been rated as ${rating === 1 ? 'poor' : 'tolerable'} and requires immediate attention to address identified deficiencies.`,
            client_response: '',
            status: 'open',
            isAutoGenerated: true,
            sourceRatingField: sourceField,
            priority: severity,
            driver_dimension: section.key
          };

          setRecommendations((prev) => {
            const filtered = prev.filter(
              (rec) => rec.hazard.trim() !== '' || rec.description.trim() !== ''
            );
            return [...filtered, newRec];
          });
        }
      } else {
        if (existingRecommendation) {
          setRecommendations((prev) =>
            prev.filter((rec) => rec.id !== existingRecommendation.id)
          );
        }
      }
    });
  }, [sectionGrades]);

  const addManualRecommendation = () => {
    const newRec: Recommendation = {
      id: crypto.randomUUID(),
      hazard: '',
      description: '',
      client_response: '',
      status: 'open',
      isAutoGenerated: false,
      priority: 'Medium'
    };
    setRecommendations([...recommendations, newRec]);
  };

  const removeRecommendation = (id: string) => {
    setRecommendations(recommendations.filter(r => r.id !== id));
  };

  const updateRecommendation = (id: string, field: keyof Recommendation, value: any) => {
    setRecommendations(recommendations.map(r => {
      if (r.id === id) {
        return { ...r, [field]: value };
      }
      return r;
    }));
  };

  const addNaturalHazard = () => {
    setNaturalHazards([
      ...naturalHazards,
      { id: crypto.randomUUID(), type: '', description: '', mitigationMeasures: '' }
    ]);
  };

  const removeNaturalHazard = (id: string) => {
    setNaturalHazards(naturalHazards.filter(h => h.id !== id));
  };

  const updateNaturalHazard = (id: string, field: keyof NaturalHazard, value: string) => {
    setNaturalHazards(naturalHazards.map(h => {
      if (h.id === id) {
        return { ...h, [field]: value };
      }
      return h;
    }));
  };

  const buildPayload = () => ({
    docControl,
    constructionElements,
    fireProtectionItems,
    commitmentLossPrevention,
    commitmentLossPrevention_rating,
    fireEquipmentTesting,
    fireEquipmentTesting_rating,
    controlHotWork,
    controlHotWork_rating,
    smoking,
    smoking_rating,
    housekeeping,
    housekeeping_rating,
    impairmentProcedures,
    impairmentProcedures_rating,
    electricalSafety,
    electricalSafety_rating,
    trainingEmergencyResponse,
    trainingEmergencyResponse_rating,
    securityArson,
    securityArson_rating,
    lossHistory,
    lossHistory_rating,
    contractorManagement,
    contractorManagement_rating,
    emergencyPlanning,
    emergencyPlanning_rating,
    selectedCurrency,
    pdSumInsured,
    biSumInsured,
    indemnityPeriod,
    emlPdPercent,
    emlBiPercent,
    mflPdPercent,
    mflBiPercent,
    lossExpectancyComments,
    naturalHazards,
    businessInterruption,
    contingencyPlanning,
    supplyChain,
    sectionGrades,
    recommendations,
  });

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const payload = buildPayload();
      const sanitized = sanitizeModuleInstancePayload(payload);

      const { error } = await supabase
        .from('module_instances')
        .update({ data: sanitized, updated_at: new Date().toISOString() })
        .eq('id', moduleInstance.id);

      if (error) throw error;

      moduleInstance.data = sanitized;

      setLastSaved(new Date().toLocaleTimeString());
      onSaved();
    } catch (error) {
      console.error('Save error:', error);
      alert('Failed to save');
    } finally {
      setIsSaving(false);
    }
  };

  const toggleSection = (sectionKey: string) => {
    setExpandedSections(prev => ({ ...prev, [sectionKey]: !prev[sectionKey] }));
  };

  const SectionHeader = ({ title, sectionKey }: { title: string; sectionKey: string }) => {
    const isExpanded = expandedSections[sectionKey] ?? true;
    return (
      <button
        type="button"
        onClick={() => toggleSection(sectionKey)}
        className="w-full flex items-center justify-between p-4 bg-neutral-50 hover:bg-neutral-100 rounded-lg transition-colors mb-4"
      >
        <h3 className="text-xl font-semibold text-neutral-900">{title}</h3>
        {isExpanded ? (
          <ChevronUp className="w-5 h-5 text-neutral-600" />
        ) : (
          <ChevronDown className="w-5 h-5 text-neutral-600" />
        )}
      </button>
    );
  };

  const isSectionExpanded = (key: string) => expandedSections[key] ?? true;

  return (
    <div className="pb-6">
      <div className="p-6 max-w-5xl mx-auto">
        <div className="mb-6 flex items-start justify-between gap-4 sticky top-0 bg-white py-4 z-10 border-b border-neutral-200">
          <div>
            <h2 className="text-2xl font-bold text-neutral-900">Risk Engineering Assessment</h2>
            <p className="text-sm text-neutral-600">
              Comprehensive property risk survey with ratings and loss analysis
            </p>
            {lastSaved && (
              <p className="text-xs text-neutral-500 mt-1">Last saved: {lastSaved}</p>
            )}
          </div>

          <button
            onClick={handleSave}
            disabled={isSaving}
            className="px-4 py-2 bg-neutral-900 text-white rounded-lg hover:bg-neutral-800 disabled:opacity-50 transition-colors"
          >
            {isSaving ? 'Saving…' : 'Save'}
          </button>
        </div>

        {/* Document Control - Always Visible */}
        <div className="mb-8 p-6 bg-neutral-50 border border-neutral-200 rounded-lg">
          <div className="flex items-center gap-3 mb-6">
            <Building2 className="w-6 h-6 text-neutral-700" />
            <h3 className="text-xl font-bold text-neutral-900">Document Control</h3>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium text-neutral-700 mb-2">
                Assessor Name
              </label>
              <input
                type="text"
                value={docControl.assessorName}
                onChange={(e) => setDocControl({ ...docControl, assessorName: e.target.value })}
                className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                placeholder="Enter assessor name"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-neutral-700 mb-2">
                Assessor Role <span className="text-neutral-400">(optional)</span>
              </label>
              <input
                type="text"
                value={docControl.assessorRole}
                onChange={(e) => setDocControl({ ...docControl, assessorRole: e.target.value })}
                className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                placeholder="e.g., Senior Risk Engineer"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-neutral-700 mb-2">
                Assessment Date
              </label>
              <input
                type="date"
                value={docControl.assessmentDate}
                onChange={(e) => setDocControl({ ...docControl, assessmentDate: e.target.value })}
                className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-neutral-700 mb-2">
                Review Date <span className="text-neutral-400">(optional)</span>
              </label>
              <input
                type="date"
                value={docControl.reviewDate}
                onChange={(e) => setDocControl({ ...docControl, reviewDate: e.target.value })}
                className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-neutral-700 mb-2">
                Client / Site Name
              </label>
              <input
                type="text"
                value={docControl.siteName}
                onChange={(e) => setDocControl({ ...docControl, siteName: e.target.value })}
                className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                placeholder="Enter client or site name"
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-neutral-700 mb-2">
                Scope / Limitations
              </label>
              <textarea
                value={docControl.scopeLimitations}
                onChange={(e) => setDocControl({ ...docControl, scopeLimitations: e.target.value })}
                rows={3}
                className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent resize-y"
                placeholder="Describe the scope and any limitations of this assessment"
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-neutral-700 mb-2">
                Standards / Frameworks
              </label>
              <textarea
                value={docControl.standardsFrameworks}
                onChange={(e) => setDocControl({ ...docControl, standardsFrameworks: e.target.value })}
                rows={2}
                className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent resize-y"
                placeholder="e.g., BS 9999, NFPA 101, FM Global standards"
              />
            </div>
          </div>
        </div>

        {/* Construction Section */}
        <div className="mb-8">
          <SectionHeader title="Construction" sectionKey="construction" />
          {isSectionExpanded('construction') && (
            <div className="space-y-4">
              <div className="overflow-x-auto bg-white border border-neutral-200 rounded-lg">
                <table className="w-full border-collapse">
                  <thead className="bg-neutral-50 border-b border-neutral-200">
                    <tr>
                      <th className="px-4 py-3 text-left text-sm font-semibold text-neutral-700">Element</th>
                      <th className="px-4 py-3 text-left text-sm font-semibold text-neutral-700">Type / Material</th>
                      <th className="px-4 py-3 text-left text-sm font-semibold text-neutral-700">Fire Resistance (mins)</th>
                      <th className="px-4 py-3 text-left text-sm font-semibold text-neutral-700">Comments</th>
                    </tr>
                  </thead>
                  <tbody>
                    {constructionElements.map((elem, idx) => (
                      <tr key={idx} className="border-b border-neutral-100 hover:bg-neutral-50">
                        <td className="px-4 py-3 font-medium text-neutral-900 bg-neutral-50">{elem.element}</td>
                        <td className="px-4 py-3">
                          <input
                            type="text"
                            value={elem.type_material}
                            onChange={(e) => {
                              const updated = [...constructionElements];
                              updated[idx].type_material = e.target.value;
                              setConstructionElements(updated);
                            }}
                            className="w-full px-3 py-2 border border-neutral-200 rounded focus:ring-2 focus:ring-neutral-400 focus:border-transparent text-sm"
                            placeholder="Steel, Concrete, Timber"
                          />
                        </td>
                        <td className="px-4 py-3">
                          <input
                            type="text"
                            value={elem.fire_resistance}
                            onChange={(e) => {
                              const updated = [...constructionElements];
                              updated[idx].fire_resistance = e.target.value;
                              setConstructionElements(updated);
                            }}
                            className="w-full px-3 py-2 border border-neutral-200 rounded focus:ring-2 focus:ring-neutral-400 focus:border-transparent text-sm"
                            placeholder="60, 120"
                          />
                        </td>
                        <td className="px-4 py-3">
                          <input
                            type="text"
                            value={elem.comments}
                            onChange={(e) => {
                              const updated = [...constructionElements];
                              updated[idx].comments = e.target.value;
                              setConstructionElements(updated);
                            }}
                            className="w-full px-3 py-2 border border-neutral-200 rounded focus:ring-2 focus:ring-neutral-400 focus:border-transparent text-sm"
                            placeholder="Additional notes"
                          />
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <SectionGrade
                sectionKey="construction"
                sectionTitle="Construction"
                value={sectionGrades.construction}
                onChange={(value) => handleSectionGradeChange('construction', value)}
              />
            </div>
          )}
        </div>

        {/* Fire Protection Systems Section */}
        <div className="mb-8">
          <SectionHeader title="Fire Protection Systems" sectionKey="fire_protection" />
          {isSectionExpanded('fire_protection') && (
            <div className="space-y-4">
              <div className="overflow-x-auto bg-white border border-neutral-200 rounded-lg">
                <table className="w-full border-collapse">
                  <thead className="bg-neutral-50 border-b border-neutral-200">
                    <tr>
                      <th className="px-4 py-3 text-left text-sm font-semibold text-neutral-700">System</th>
                      <th className="px-4 py-3 text-left text-sm font-semibold text-neutral-700">Provided?</th>
                      <th className="px-4 py-3 text-left text-sm font-semibold text-neutral-700">Coverage / Extent</th>
                      <th className="px-4 py-3 text-left text-sm font-semibold text-neutral-700">Standard</th>
                      <th className="px-4 py-3 text-left text-sm font-semibold text-neutral-700">Comments</th>
                    </tr>
                  </thead>
                  <tbody>
                    {fireProtectionItems.map((item, idx) => (
                      <tr key={idx} className="border-b border-neutral-100 hover:bg-neutral-50">
                        <td className="px-4 py-3 font-medium text-neutral-900 bg-neutral-50">{item.system}</td>
                        <td className="px-4 py-3">
                          <select
                            value={item.provided}
                            onChange={(e) => {
                              const updated = [...fireProtectionItems];
                              updated[idx].provided = e.target.value;
                              setFireProtectionItems(updated);
                            }}
                            className="w-full px-3 py-2 border border-neutral-200 rounded focus:ring-2 focus:ring-neutral-400 focus:border-transparent text-sm"
                          >
                            <option value="No">No</option>
                            <option value="Yes">Yes</option>
                            <option value="Partial">Partial</option>
                          </select>
                        </td>
                        <td className="px-4 py-3">
                          <input
                            type="text"
                            value={item.coverage_extent}
                            onChange={(e) => {
                              const updated = [...fireProtectionItems];
                              updated[idx].coverage_extent = e.target.value;
                              setFireProtectionItems(updated);
                            }}
                            className="w-full px-3 py-2 border border-neutral-200 rounded focus:ring-2 focus:ring-neutral-400 focus:border-transparent text-sm"
                            placeholder="Full, partial, zones"
                          />
                        </td>
                        <td className="px-4 py-3">
                          <input
                            type="text"
                            value={item.standard}
                            onChange={(e) => {
                              const updated = [...fireProtectionItems];
                              updated[idx].standard = e.target.value;
                              setFireProtectionItems(updated);
                            }}
                            className="w-full px-3 py-2 border border-neutral-200 rounded focus:ring-2 focus:ring-neutral-400 focus:border-transparent text-sm"
                            placeholder="BS, NFPA, FM"
                          />
                        </td>
                        <td className="px-4 py-3">
                          <input
                            type="text"
                            value={item.comments}
                            onChange={(e) => {
                              const updated = [...fireProtectionItems];
                              updated[idx].comments = e.target.value;
                              setFireProtectionItems(updated);
                            }}
                            className="w-full px-3 py-2 border border-neutral-200 rounded focus:ring-2 focus:ring-neutral-400 focus:border-transparent text-sm"
                            placeholder="Additional notes"
                          />
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <SectionGrade
                sectionKey="fire_protection"
                sectionTitle="Fire Protection"
                value={sectionGrades.fire_protection}
                onChange={(value) => handleSectionGradeChange('fire_protection', value)}
              />
            </div>
          )}
        </div>

        {/* Management Systems Section */}
        <div className="mb-8">
          <SectionHeader title="Management Systems" sectionKey="management_systems" />
          {isSectionExpanded('management_systems') && (
            <div className="space-y-6">
              {[
                { label: 'Commitment to Loss Prevention', value: commitmentLossPrevention, setValue: setCommitmentLossPrevention, rating: commitmentLossPrevention_rating, setRating: setCommitmentLossPreventionRating },
                { label: 'Fire Equipment Testing & Maintenance', value: fireEquipmentTesting, setValue: setFireEquipmentTesting, rating: fireEquipmentTesting_rating, setRating: setFireEquipmentTestingRating },
                { label: 'Control of Hot Work', value: controlHotWork, setValue: setControlHotWork, rating: controlHotWork_rating, setRating: setControlHotWorkRating },
                { label: 'Smoking Policy', value: smoking, setValue: setSmoking, rating: smoking_rating, setRating: setSmokingRating },
                { label: 'Housekeeping', value: housekeeping, setValue: setHousekeeping, rating: housekeeping_rating, setRating: setHousekeepingRating },
                { label: 'Impairment Procedures', value: impairmentProcedures, setValue: setImpairmentProcedures, rating: impairmentProcedures_rating, setRating: setImpairmentProceduresRating },
                { label: 'Electrical Safety', value: electricalSafety, setValue: setElectricalSafety, rating: electricalSafety_rating, setRating: setElectricalSafetyRating },
                { label: 'Training & Emergency Response', value: trainingEmergencyResponse, setValue: setTrainingEmergencyResponse, rating: trainingEmergencyResponse_rating, setRating: setTrainingEmergencyResponseRating },
                { label: 'Security & Arson Prevention', value: securityArson, setValue: setSecurityArson, rating: securityArson_rating, setRating: setSecurityArsonRating },
                { label: 'Loss History', value: lossHistory, setValue: setLossHistory, rating: lossHistory_rating, setRating: setLossHistoryRating },
                { label: 'Contractor Management', value: contractorManagement, setValue: setContractorManagement, rating: contractorManagement_rating, setRating: setContractorManagementRating },
                { label: 'Emergency Planning', value: emergencyPlanning, setValue: setEmergencyPlanning, rating: emergencyPlanning_rating, setRating: setEmergencyPlanningRating },
              ].map((field, idx) => (
                <div key={idx} className="p-4 bg-neutral-50 rounded-lg border border-neutral-200">
                  <label className="block text-sm font-medium text-neutral-700 mb-2">
                    {field.label}
                  </label>
                  <textarea
                    value={field.value}
                    onChange={(e) => field.setValue(e.target.value)}
                    rows={2}
                    className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent transition-all resize-y mb-3"
                    placeholder={`Describe ${field.label.toLowerCase()}`}
                  />
                  <RatingRadio
                    value={field.rating}
                    onChange={field.setRating}
                  />
                </div>
              ))}

              <SectionGrade
                sectionKey="management_systems"
                sectionTitle="Management Systems"
                value={sectionGrades.management_systems}
                onChange={(value) => handleSectionGradeChange('management_systems', value)}
              />
            </div>
          )}
        </div>

        {/* Natural Hazards Section */}
        <div className="mb-8">
          <SectionHeader title="Natural Hazards" sectionKey="natural_hazards" />
          {isSectionExpanded('natural_hazards') && (
            <div className="space-y-4">
              <button
                type="button"
                onClick={addNaturalHazard}
                className="flex items-center gap-2 px-4 py-2 bg-neutral-900 text-white rounded-lg hover:bg-neutral-800 transition-colors text-sm"
              >
                <Plus className="w-4 h-4" />
                Add Natural Hazard
              </button>

              {naturalHazards.length === 0 ? (
                <div className="text-center py-8 border-2 border-dashed border-neutral-300 rounded-lg">
                  <p className="text-neutral-600">No natural hazards recorded. Click above to add.</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {naturalHazards.map((hazard) => (
                    <div key={hazard.id} className="p-4 border border-neutral-300 rounded-lg bg-white">
                      <div className="flex items-start justify-between gap-4 mb-3">
                        <input
                          type="text"
                          value={hazard.type}
                          onChange={(e) => updateNaturalHazard(hazard.id, 'type', e.target.value)}
                          className="flex-1 px-3 py-2 border border-neutral-300 rounded-lg text-sm font-medium"
                          placeholder="Hazard type (e.g., Flood, Earthquake)"
                        />
                        <button
                          type="button"
                          onClick={() => removeNaturalHazard(hazard.id)}
                          className="text-red-600 hover:text-red-700 hover:bg-red-50 p-2 rounded-lg transition-all"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>

                      <div className="space-y-3">
                        <div>
                          <label className="block text-sm font-medium text-neutral-700 mb-1">
                            Description
                          </label>
                          <textarea
                            value={hazard.description}
                            onChange={(e) => updateNaturalHazard(hazard.id, 'description', e.target.value)}
                            rows={2}
                            className="w-full px-3 py-2 border border-neutral-300 rounded-lg text-sm"
                            placeholder="Describe the hazard and its potential impact"
                          />
                        </div>

                        <div>
                          <label className="block text-sm font-medium text-neutral-700 mb-1">
                            Mitigation Measures
                          </label>
                          <textarea
                            value={hazard.mitigationMeasures}
                            onChange={(e) => updateNaturalHazard(hazard.id, 'mitigationMeasures', e.target.value)}
                            rows={2}
                            className="w-full px-3 py-2 border border-neutral-300 rounded-lg text-sm"
                            placeholder="Describe mitigation and protection measures in place"
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              <SectionGrade
                sectionKey="natural_hazards"
                sectionTitle="Natural Hazards"
                value={sectionGrades.natural_hazards}
                onChange={(value) => handleSectionGradeChange('natural_hazards', value)}
              />
            </div>
          )}
        </div>

        {/* Business Continuity Section */}
        <div className="mb-8">
          <SectionHeader title="Business Continuity" sectionKey="business_continuity" />
          {isSectionExpanded('business_continuity') && (
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  Business Interruption Considerations
                </label>
                <textarea
                  value={businessInterruption}
                  onChange={(e) => setBusinessInterruption(e.target.value)}
                  rows={4}
                  className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent transition-all resize-y"
                  placeholder="Describe business interruption considerations"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  Contingency Planning
                </label>
                <textarea
                  value={contingencyPlanning}
                  onChange={(e) => setContingencyPlanning(e.target.value)}
                  rows={4}
                  className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent transition-all resize-y"
                  placeholder="Describe contingency planning"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  Supply Chain
                </label>
                <textarea
                  value={supplyChain}
                  onChange={(e) => setSupplyChain(e.target.value)}
                  rows={4}
                  className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent transition-all resize-y"
                  placeholder="Describe supply chain considerations"
                />
              </div>

              <SectionGrade
                sectionKey="business_continuity"
                sectionTitle="Business Continuity"
                value={sectionGrades.business_continuity}
                onChange={(value) => handleSectionGradeChange('business_continuity', value)}
              />
            </div>
          )}
        </div>

        {/* Loss Expectancy Section */}
        <div className="mb-8">
          <SectionHeader title="Loss Expectancy" sectionKey="loss_expectancy" />
          {isSectionExpanded('loss_expectancy') && (
            <div className="space-y-6">
              <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <h4 className="text-sm font-semibold text-blue-900 mb-2">Sums Insured</h4>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">
                      Currency
                    </label>
                    <select
                      value={selectedCurrency}
                      onChange={(e) => setSelectedCurrency(e.target.value)}
                      className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                    >
                      <option value="GBP">GBP (£)</option>
                      <option value="USD">USD ($)</option>
                      <option value="EUR">EUR (€)</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">
                      Indemnity Period (months)
                    </label>
                    <input
                      type="number"
                      value={indemnityPeriod}
                      onChange={(e) => setIndemnityPeriod(e.target.value)}
                      className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                      placeholder="12"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">
                      Property Damage Sum Insured
                    </label>
                    <input
                      type="number"
                      value={pdSumInsured}
                      onChange={(e) => setPdSumInsured(e.target.value)}
                      className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                      placeholder="0"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">
                      Business Interruption Sum Insured
                    </label>
                    <input
                      type="number"
                      value={biSumInsured}
                      onChange={(e) => setBiSumInsured(e.target.value)}
                      className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                      placeholder="0"
                    />
                  </div>
                </div>
              </div>

              {/* Loss Metrics Summary Card */}
              <div className="p-6 bg-gradient-to-br from-neutral-50 to-neutral-100 border border-neutral-300 rounded-lg shadow-sm">
                <h4 className="text-base font-semibold text-neutral-900 mb-4">Loss Metrics Summary</h4>

                <div className="space-y-6">
                  <div className="grid grid-cols-2 gap-4">
                    <div className="bg-white p-4 rounded-lg border border-neutral-200">
                      <div className="text-xs font-medium text-neutral-500 uppercase tracking-wide mb-1">PD Sum Insured</div>
                      <div className="text-2xl font-bold text-neutral-900">{formatCurrency(pd)}</div>
                    </div>
                    <div className="bg-white p-4 rounded-lg border border-neutral-200">
                      <div className="text-xs font-medium text-neutral-500 uppercase tracking-wide mb-1">BI Sum Insured</div>
                      <div className="text-2xl font-bold text-neutral-900">{formatCurrency(bi)}</div>
                    </div>
                  </div>

                  <div className="border-t border-neutral-300 pt-4">
                    <div className="text-xs font-semibold text-orange-700 uppercase tracking-wide mb-3">Estimated Maximum Loss (EML)</div>
                    <div className="grid grid-cols-3 gap-4">
                      <div className="bg-white p-3 rounded-lg border border-orange-200">
                        <div className="text-xs text-neutral-600 mb-1">EML PD</div>
                        <div className="text-lg font-bold text-neutral-900">{formatCurrency(emlPd)}</div>
                      </div>
                      <div className="bg-white p-3 rounded-lg border border-orange-200">
                        <div className="text-xs text-neutral-600 mb-1">EML BI</div>
                        <div className="text-lg font-bold text-neutral-900">{formatCurrency(emlBi)}</div>
                      </div>
                      <div className="bg-orange-50 p-3 rounded-lg border-2 border-orange-400">
                        <div className="text-xs text-orange-700 font-medium mb-1">EML Total</div>
                        <div className="text-lg font-bold text-orange-700">{formatCurrency(emlTotal)}</div>
                      </div>
                    </div>
                  </div>

                  <div className="border-t border-neutral-300 pt-4">
                    <div className="text-xs font-semibold text-red-700 uppercase tracking-wide mb-3">Maximum Foreseeable Loss (MFL)</div>
                    <div className="grid grid-cols-3 gap-4">
                      <div className="bg-white p-3 rounded-lg border border-red-200">
                        <div className="text-xs text-neutral-600 mb-1">MFL PD</div>
                        <div className="text-lg font-bold text-neutral-900">{formatCurrency(mflPd)}</div>
                      </div>
                      <div className="bg-white p-3 rounded-lg border border-red-200">
                        <div className="text-xs text-neutral-600 mb-1">MFL BI</div>
                        <div className="text-lg font-bold text-neutral-900">{formatCurrency(mflBi)}</div>
                      </div>
                      <div className="bg-red-50 p-3 rounded-lg border-2 border-red-400">
                        <div className="text-xs text-red-700 font-medium mb-1">MFL Total</div>
                        <div className="text-lg font-bold text-red-700">{formatCurrency(mflTotal)}</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="p-4 bg-orange-50 border border-orange-200 rounded-lg">
                <h4 className="text-sm font-semibold text-orange-900 mb-4">Estimated Maximum Loss (EML)</h4>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">
                      EML PD % (0-100)
                    </label>
                    <input
                      type="number"
                      min="0"
                      max="100"
                      value={emlPdPercent}
                      onChange={(e) => setEmlPdPercent(parseFloat(e.target.value) || 0)}
                      className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">
                      EML BI % (0-100)
                    </label>
                    <input
                      type="number"
                      min="0"
                      max="100"
                      value={emlBiPercent}
                      onChange={(e) => setEmlBiPercent(parseFloat(e.target.value) || 0)}
                      className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                    />
                  </div>
                </div>

                <div className="bg-white p-4 rounded-lg border border-orange-300">
                  <div className="grid grid-cols-3 gap-4 text-sm">
                    <div>
                      <div className="text-neutral-600 mb-1">EML PD</div>
                      <div className="text-lg font-bold text-neutral-900">{formatCurrency(emlPd)}</div>
                    </div>
                    <div>
                      <div className="text-neutral-600 mb-1">EML BI</div>
                      <div className="text-lg font-bold text-neutral-900">{formatCurrency(emlBi)}</div>
                    </div>
                    <div>
                      <div className="text-neutral-600 mb-1">EML Total</div>
                      <div className="text-lg font-bold text-orange-700">{formatCurrency(emlTotal)}</div>
                    </div>
                  </div>
                </div>
              </div>

              <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
                <h4 className="text-sm font-semibold text-red-900 mb-4">Maximum Foreseeable Loss (MFL)</h4>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">
                      MFL PD % (0-100)
                    </label>
                    <input
                      type="number"
                      min="0"
                      max="100"
                      value={mflPdPercent}
                      onChange={(e) => setMflPdPercent(parseFloat(e.target.value) || 0)}
                      className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-2">
                      MFL BI % (0-100)
                    </label>
                    <input
                      type="number"
                      min="0"
                      max="100"
                      value={mflBiPercent}
                      onChange={(e) => setMflBiPercent(parseFloat(e.target.value) || 0)}
                      className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent"
                    />
                  </div>
                </div>

                <div className="bg-white p-4 rounded-lg border border-red-300">
                  <div className="grid grid-cols-3 gap-4 text-sm">
                    <div>
                      <div className="text-neutral-600 mb-1">MFL PD</div>
                      <div className="text-lg font-bold text-neutral-900">{formatCurrency(mflPd)}</div>
                    </div>
                    <div>
                      <div className="text-neutral-600 mb-1">MFL BI</div>
                      <div className="text-lg font-bold text-neutral-900">{formatCurrency(mflBi)}</div>
                    </div>
                    <div>
                      <div className="text-neutral-600 mb-1">MFL Total</div>
                      <div className="text-lg font-bold text-red-700">{formatCurrency(mflTotal)}</div>
                    </div>
                  </div>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-neutral-700 mb-2">
                  Loss Expectancy Comments
                </label>
                <textarea
                  value={lossExpectancyComments}
                  onChange={(e) => setLossExpectancyComments(e.target.value)}
                  rows={4}
                  className="w-full px-4 py-2.5 border border-neutral-300 rounded-lg focus:ring-2 focus:ring-neutral-500 focus:border-transparent transition-all resize-y"
                  placeholder="Additional comments on loss expectancy scenarios"
                />
              </div>

              <SectionGrade
                sectionKey="loss_expectancy"
                sectionTitle="Loss Expectancy"
                value={sectionGrades.loss_expectancy}
                onChange={(value) => handleSectionGradeChange('loss_expectancy', value)}
              />
            </div>
          )}
        </div>

        {/* Recommendations Section */}
        <div className="mb-8">
          <SectionHeader title="Recommendations" sectionKey="recommendations" />
          {isSectionExpanded('recommendations') && (
            <div className="space-y-4">
              <div className="flex items-center justify-between gap-4 mb-4">
                <p className="text-sm text-neutral-600">
                  Recommendations are auto-generated based on section ratings (1-2), or you can add manual recommendations.
                </p>
                <div className="flex gap-2">
                  <button
                    type="button"
                    onClick={addManualRecommendation}
                    className="flex items-center gap-2 px-4 py-2 bg-neutral-900 text-white rounded-lg hover:bg-neutral-800 transition-colors text-sm"
                  >
                    <Plus className="w-4 h-4" />
                    Add Manual
                  </button>
                </div>
              </div>

              {recommendations.length === 0 ? (
                <div className="text-center py-8 border-2 border-dashed border-neutral-300 rounded-lg">
                  <p className="text-neutral-600">No recommendations yet. Rate sections 1-2 to auto-generate, or add manually.</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {recommendations.map((rec, idx) => (
                    <div
                      key={rec.id}
                      className={`p-4 border rounded-lg ${rec.isAutoGenerated ? 'bg-blue-50 border-blue-200' : 'bg-white border-neutral-300'}`}
                    >
                      <div className="flex items-start justify-between gap-4 mb-3">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-2">
                            <span className="text-xs font-medium px-2 py-1 rounded bg-neutral-200 text-neutral-700">
                              #{idx + 1}
                            </span>
                            {rec.priority && (
                              <span className={`text-xs font-medium px-2 py-1 rounded ${
                                rec.priority === 'Critical' ? 'bg-red-100 text-red-700' :
                                rec.priority === 'High' ? 'bg-orange-100 text-orange-700' :
                                rec.priority === 'Medium' ? 'bg-yellow-100 text-yellow-700' :
                                'bg-green-100 text-green-700'
                              }`}>
                                {rec.priority}
                              </span>
                            )}
                            {rec.isAutoGenerated && (
                              <span className="text-xs font-medium px-2 py-1 rounded bg-blue-100 text-blue-700">
                                Auto-Generated
                              </span>
                            )}
                          </div>
                        </div>
                        <button
                          type="button"
                          onClick={() => removeRecommendation(rec.id)}
                          className="text-red-600 hover:text-red-700 hover:bg-red-50 p-2 rounded-lg transition-all"
                          disabled={rec.isAutoGenerated}
                          title={rec.isAutoGenerated ? "Auto-generated recommendations are removed when rating improves" : "Remove recommendation"}
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>

                      <div className="space-y-3">
                        <div>
                          <label className="block text-sm font-medium text-neutral-700 mb-1">
                            Hazard / Finding
                          </label>
                          <input
                            type="text"
                            value={rec.hazard}
                            onChange={(e) => updateRecommendation(rec.id, 'hazard', e.target.value)}
                            className="w-full px-3 py-2 border border-neutral-300 rounded-lg text-sm"
                            placeholder="Brief title of the hazard or finding"
                            disabled={rec.isAutoGenerated}
                          />
                        </div>

                        <div>
                          <label className="block text-sm font-medium text-neutral-700 mb-1">
                            Description / Recommended Action
                          </label>
                          <textarea
                            value={rec.description}
                            onChange={(e) => updateRecommendation(rec.id, 'description', e.target.value)}
                            rows={3}
                            className="w-full px-3 py-2 border border-neutral-300 rounded-lg text-sm"
                            placeholder="Detailed description and recommended action"
                          />
                        </div>

                        <div>
                          <label className="block text-sm font-medium text-neutral-700 mb-1">
                            Client Response (Optional)
                          </label>
                          <textarea
                            value={rec.client_response}
                            onChange={(e) => updateRecommendation(rec.id, 'client_response', e.target.value)}
                            rows={2}
                            className="w-full px-3 py-2 border border-neutral-300 rounded-lg text-sm"
                            placeholder="Client's response or action taken"
                          />
                        </div>

                        <div className="grid grid-cols-2 gap-3">
                          <div>
                            <label className="block text-sm font-medium text-neutral-700 mb-1">
                              Status
                            </label>
                            <select
                              value={rec.status}
                              onChange={(e) => updateRecommendation(rec.id, 'status', e.target.value)}
                              className="w-full px-3 py-2 border border-neutral-300 rounded-lg text-sm"
                            >
                              <option value="open">Open</option>
                              <option value="in_progress">In Progress</option>
                              <option value="completed">Completed</option>
                              <option value="closed">Closed</option>
                            </select>
                          </div>

                          {!rec.isAutoGenerated && (
                            <div>
                              <label className="block text-sm font-medium text-neutral-700 mb-1">
                                Priority
                              </label>
                              <select
                                value={rec.priority || 'Medium'}
                                onChange={(e) => updateRecommendation(rec.id, 'priority', e.target.value)}
                                className="w-full px-3 py-2 border border-neutral-300 rounded-lg text-sm"
                              >
                                <option value="Critical">Critical</option>
                                <option value="High">High</option>
                                <option value="Medium">Medium</option>
                                <option value="Low">Low</option>
                              </select>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>

        {document?.id && moduleInstance?.id && (
          <ModuleActions
            documentId={document.id}
            moduleInstanceId={moduleInstance.id}
          />
        )}

        <OutcomePanel
          moduleInstance={moduleInstance}
          document={document}
          onUpdate={onSaved}
        />
      </div>
    </div>
  );
}
